spring.application.name=cosmic-cats
server.port=8080

# application.properties
application.base-url=/api/v1/products
application.integration.rest-client.connect-timeout-millis=500
application.integration.rest-client.read-timeout-millis=2000
application.integration.rest-client.retries=2
application.integration.rest-client.timeout-on-failure-millis=1000

application.competitors-price-observer.url-wildcard = http://localhost:8081/competitors-price-observer/v1/product/{productId}/prices
