services:
  postgres:
    image: postgres
    container_name: postgres_intergalactic_storage
    environment:
      POSTGRES_DB: "cosmic_cats"
      POSTGRES_USER: "cosmic-cat"
      POSTGRES_PASSWORD: "cosmic-password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
