openapi: 3.0.1
info:
  title: Product API
  version: 1.0.0
paths:
  /api/v1/products:
    get:
      summary: List of all Products
      tags:
      - Products
      operationId: getProducts
      responses:
        "200":
          description: List of all Products
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"
    post:
      summary: Create a new Product
      tags:
      - Products
      operationId: createProduct
      requestBody:
        description: Product data to create a new Product
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreationDto"
        required: true
      responses:
        "201":
          description: Product created successfully
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ProductDto"
        "400":
          description: Invalid input, some of the fields passed failed validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
  /api/v1/products/{id}:
    get:
      summary: Get a Product by its UUID
      tags:
      - Products
      operationId: getProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDto"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
    put:
      tags:
      - Products
      operationId: updateProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreationDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ProductDto"
    delete:
      tags:
      - Products
      operationId: deleteProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
  /api/v1/products/{id}/competitor-price-observer:
    get:
      summary: List market competitors who sell the same Product in all the galaxies
      tags:
      - Product
      - MarketCompetitor
      operationId: getOtherStoresPrices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitorsObserverResponseDto"
  /api/v1/products/kitty-products:
    get:
      summary: List all the products for kitties (who are tiny chaos machines)
      tags:
        - Product
        - Audience
      operationId: getProductsForKitties
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"
        "404":
          description: Functionality is disabled by Feature Toggle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
  /api/v1/products/junior-cat-products:
    get:
      summary: List all the products for junior cats (who are feline teens, cute but rebellious)
      tags:
        - Product
        - Audience
      operationId: getProductsForJuniorCats
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"
        "404":
          description: Functionality is disabled by Feature Toggle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
  /api/v1/products/senior-cat-products:
    get:
      summary: List all the products for senior cats (who are mature meowsters of the universe)
      tags:
        - Product
        - Audience
      operationId: getProductsForSeniorCats
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"
        "404":
          description: Functionality is disabled by Feature Toggle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
components:
  schemas:
    ProductCreationDto:
      required:
      - category
      - name
      type: object
      properties:
        category:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        targetAudience:
          type: string
          enum:
          - CustomerType.KITTY(customerTypeName=kitty)
          - CustomerType.JUNIOR_CAT(customerTypeName=junior-cat)
          - CustomerType.SENIOR_CAT(customerTypeName=senior-cat)
    ProductDto:
      required:
      - category
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        category:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        targetAudience:
          type: string
          enum:
          - CustomerType.KITTY(customerTypeName=kitty)
          - CustomerType.JUNIOR_CAT(customerTypeName=junior-cat)
          - CustomerType.SENIOR_CAT(customerTypeName=senior-cat)
    CompetitorStorePrice:
      type: object
      properties:
        storeName:
          type: string
        regularPrice:
          type: number
          format: double
        markedDownPrice:
          type: number
          format: double
    CompetitorsObserverResponseDto:
      type: object
      properties:
        productUuid:
          type: string
          format: uuid
        stores:
          type: array
          items:
            $ref: "#/components/schemas/CompetitorStorePrice"
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
          example: "product-not-found"
        title:
          type: string
          example: "Product Not Found"
        status:
          type: integer
          example: 404
        detail:
          type: string
          example: "Product with id: id does not exist. There is nothing to delete!"
        "instance":
          type: string
          example: "/api/v1/products/77777777-0000-0000-0000-000000000010"